version: '3.1'

services:
  frontend:
    build:
      context: ./front/
      dockerfile: Dockerfile
    ports:
      - "3000:443"
  backend:
    build:
      context: ./back/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
