# Generated by Django 5.0.1 on 2024-03-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
