# Generated by Django 5.0.1 on 2024-03-24 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0003_category_flower_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RestAPI.category'),
        ),
    ]
