# Generated by Django 5.0.1 on 2024-05-19 08:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RestAPI', '0006_alter_flower_price_alter_flower_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Basket',
            new_name='Order',
        ),
    ]
